export const transactions = [
  {
    id: 1,
    transactionType: "Deposit",
    amount: "+500",
    currency: "AUD",
    date: new Date("2024-04-16"),
    type: "Blockchain Wallet",
    status: "Complete",
  },
  {
    id: 2,
    transactionType: "Withdraw",
    amount: "-600",
    currency: "AUD",
    date: new Date("2024-04-15"),
    type: "Blockchain Wallet",
    status: "Complete",
  },
  {
    id: 3,
    transactionType: "Deposit",
    amount: "+100",
    currency: "AUD",
    date: new Date("2024-04-13"),
    type: "Blockchain Wallet",
    status: "Complete",
  },
  {
    id: 4,
    transactionType: "Deposit",
    amount: "+100",
    currency: "AUD",
    date: new Date("2024-04-12"),
    type: "Blockchain Wallet",
    status: "Complete",
  },
  {
    id: 5,
    transactionType: "Withdraw",
    amount: "-2,100",
    currency: "AUD",
    date: new Date("2024-04-10"),
    type: "Bank Wire",
    status: "Complete",
  },
  {
    id: 1,
    transactionType: "Deposit",
    amount: "+100",
    currency: "AUD",
    date: new Date("2024-03-25"),
    type: "Blockchain Wallet",
    status: "Complete",
  },
  {
    id: 1,
    transactionType: "Deposit",
    amount: "+100",
    currency: "AUD",
    date: new Date("2024-02-21"),
    type: "Blockchain Wallet",
    status: "Complete",
  },
  {
    id: 1,
    transactionType: "Withdraw",
    amount: "-6,300",
    currency: "AUD",
    date: new Date("2024-02-15"),
    type: "Bank Wire",
    status: "Complete",
  },
  {
    id: 1,
    transactionType: "Deposit",
    amount: "+4,000",
    currency: "AUD",
    date: new Date("2024-02-13"),
    type: "Blockchain Wallet",
    status: "Complete",
  },
  {
    id: 1,
    transactionType: "Deposit",
    amount: "+100",
    currency: "AUD",
    date: new Date("2024-02-09"),
    type: "Blockchain Wallet",
    status: "Complete",
  },
  {
    id: 1,
    transactionType: "Deposit",
    amount: "+100",
    currency: "AUD",
    date: new Date("2024-02-04"),
    type: "Blockchain Wallet",
    status: "Complete",
  },
];
